### PR TITLE
feat(validators): Adding Joi validation

### PR DESCRIPTION
**Pull request by shraddha1704**
### What
Add Joi validation to POST /movies request

### Why
Miyagi training

### CODE REVIEW

**Comment by ben174** [comment]
Shouldn't there be a travis integration?

**Comment by jesscxu** [comment]
oh, ya shouldn't there be a travis integration set up at this point? also can you add validator tests @shraddha1704

**Comment by shraddha1704** [comment]
> Shouldn't there be a travis integration?



> Shouldn't there be a travis integration?

**Comment by shraddha1704** [comment]
Sorry! I had to create a new repository and forgot to turn on travis-ci for it.

**Comment by shraddha1704** [comment]
@jesscxu Validator test is the next task. I'll put up a PR for that once I merge this one

**Comment by ben174** [comment]
lgtm

**Comment by ben174** [comment]
lgtm

**Review by ben174 — APPROVED** [review]

**Review by jesscxu — APPROVED** [review]
LGTM

**Pull request merged**
